name: Samples
on:
  push:
    branches: master
    tags: '**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build
      run: dotnet build ./samples -c Release
    - name: Test
      working-directory: samples
      run: dotnet test ./samples -c Release --no-build
      
  pack:
      runs-on: ubuntu-latest
      needs: build
      if: github.event_name == 'push'
      steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.108
      - name: Pack
        run: dotnet pack -o ./artifacts -c Release
      - uses: actions/upload-artifact@v1
        with:
          name: artifacts
          path: ./artifacts
